AllCops:
  TargetRubyVersion: 2.4
Rails:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/LineLength:
  Max: 100

Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SymbolArray:
  Enabled: false
