require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'db/**/*'

Layout/EndOfLine:
  EnforcedStyle: lf
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/LineLength:
  Max: 100

Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SymbolArray:
  Enabled: false
