version: 2.1 # use CircleCI 2.1

common_env: &common_env
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
  BUNDLE_PATH: vendor/bundle
  DB_HOST: 127.0.0.1
  DB_PASSWORD: ''
  DB_USERNAME: 'root'
  MYSQL_ALLOW_EMPTY_PASSWORD: yes
  RAILS_ENV: test
  TZ: 'Asia/Tokyo'

executors:
  latest:
    docker:
      - image: circleci/ruby:latest
    environment:
      <<: *common_env
  node-browsers-2-5:
    docker:
      - image: circleci/ruby:2.5-node-browsers
      - image: redis:4.0.14
      - image: circleci/mariadb:10.4.11
    environment:
      <<: *common_env
  node-browsers-2-6:
    docker:
      - image: circleci/ruby:2.6-node-browsers
      - image: redis:4.0.14
      - image: circleci/mariadb:10.4.11
    environment:
      <<: *common_env
  node-browsers-latest:
    docker:
      - image: circleci/ruby:latest-node-browsers
      - image: redis:4.0.14
      - image: circleci/mariadb:10.4.11
    environment:
      <<: *common_env

commands:
  update_rubygems:
    steps:
      - run:
          name: Setup RubyGems and Bundler
          command: |-
            sudo gem update --system
  which_bundler:
    steps:
      - run:
          name: Which bundler?
          command: bundle -v
  which_ruby:
    steps:
      - run:
          name: Which Ruby?
          command: ruby -v
  # Restore bundle cache
  # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
  restore_gems:
    parameters:
      ruby-version:
        type: string
    steps:
      - restore_cache:
          keys:
            - bundle-v2-<< parameters.ruby-version >>-{{ checksum "Gemfile.lock" }}
            - bundle-v2-
  # Install Ruby dependencies
  install_gems:
    steps:
      - run:
          name: Bundle Install
          command: bundle check || bundle install
  # Store bundle cache for Ruby dependencies
  save_gems:
    parameters:
      ruby-version:
        type: string
    steps:
      - save_cache:
          key: bundle-v2-<< parameters.ruby-version >>-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  wait_for_db:
    steps:
    - run:
        name: Wait for DB
        command: dockerize -wait tcp://127.0.0.1:3306 -timeout 60s
  setup_database:
    steps:
      - run:
          name: Database setup
          command: |-
            bin/rails db:create --trace
            bin/rails db:schema:load --trace
  setup_test_reporter:
    steps:
      - run:
          name: Setup Code Climate test-reporter
          command: |-
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
  minitest:
    steps:
      - run:
          name: Run minitest
          command: |-
            bundle exec rails test
  system_test:
    steps:
      - run:
          name: Run system test
          command: |-
            bundle exec rails test:system
      - store_artifacts:
          path: tmp/screenshots
  store_test_reports:
    steps:
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test/reports

jobs: # a collection of steps
  brakeman:
    executor: latest
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: latest
      - install_gems
      - save_gems:
          ruby-version: latest
      - run:
          name: Run Brakeman
          command: |-
            bundle exec brakeman
  minitest-2-5:
    executor: node-browsers-2-5
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.5'
      - install_gems
      - save_gems:
          ruby-version: '2.5'
      - wait_for_db
      - setup_database
      - minitest
      - store_test_reports
  system-test-2-5:
    executor: node-browsers-2-5
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.5'
      - install_gems
      - save_gems:
          ruby-version: '2.5'
      - wait_for_db
      - setup_database
      - system_test
      - store_test_reports
  minitest-2-6:
    executor: node-browsers-2-6
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.6'
      - install_gems
      - save_gems:
          ruby-version: '2.6'
      - wait_for_db
      - setup_database
      - minitest
      - store_test_reports
  system-test-2-6:
    executor: node-browsers-2-6
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.6'
      - install_gems
      - save_gems:
          ruby-version: '2.6'
      - wait_for_db
      - setup_database
      - system_test
      - store_test_reports
  minitest-latest:
    executor: node-browsers-latest
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: latest
      - install_gems
      - save_gems:
          ruby-version: latest
      - wait_for_db
      - setup_database
      - setup_test_reporter
      - minitest
      - run:
          name: Upload test coverage
          command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      - store_test_reports
  system-test-latest:
    executor: node-browsers-latest
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: latest
      - install_gems
      - save_gems:
          ruby-version: latest
      - wait_for_db
      - setup_database
      - system_test
      - store_test_reports

workflows:
  version: 2.1
  brakeman:
    jobs:
      - brakeman
  ruby-2.5-test:
    jobs:
      - minitest-2-5
      - system-test-2-5
  ruby-2.6-test:
    jobs:
      - minitest-2-6
      - system-test-2-6
  ruby-latest-test:
    jobs:
      - minitest-latest
      - system-test-latest
