usd_jpy_m1_candle_job:
  cron: '*/10 * * * *'
  class: 'UsdJpyM1CandleJob'
  queue: 'normal'
  args:
  description: 'USD/JPY の1分足ローソク取得ジョブ'
eur_jpy_m1_candle_job:
  cron: '*/10 * * * *'
  class: 'EurJpyM1CandleJob'
  queue: 'normal'
  args:
  description: 'EUR/JPY の1分足ローソク取得ジョブ'
gbp_jpy_m1_candle_job:
  cron: '*/10 * * * *'
  class: 'GbpJpyM1CandleJob'
  queue: 'normal'
  args:
  description: 'GBP/JPY の1分足ローソク取得ジョブ'
